import type { Sprint } from './domain/entities/Sprint';
import type { UserStory } from './domain/entities/UserStory';
import type { ProgressRecord } from './domain/entities/ProgressRecord';
import type { Developer } from './domain/entities/Developer';
import type { SprintHoliday } from './domain/entities/SprintHoliday';
import type { DeveloperAvailability } from './domain/entities/DeveloperAvailability';

export const MOCK_DEVELOPERS: Developer[] = [
  {
    id: 'dev-1',
    name: 'Alice Johnson',
    email: 'alice@company.com',
    role: 'Senior Frontend Dev',
    avatarColor: '#6366f1',
    isActive: true,
  },
  {
    id: 'dev-2',
    name: 'Bob Martinez',
    email: 'bob@company.com',
    role: 'Backend Developer',
    avatarColor: '#10b981',
    isActive: true,
  },
  {
    id: 'dev-3',
    name: 'Carol Smith',
    email: 'carol@company.com',
    role: 'Full Stack Developer',
    avatarColor: '#f59e0b',
    isActive: true,
  },
  {
    id: 'dev-4',
    name: 'David Lee',
    email: 'david@company.com',
    role: 'QA Engineer',
    avatarColor: '#ec4899',
    isActive: true,
  },
];

export const MOCK_SPRINTS: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 12 - User Auth',
    goal: 'Implement complete user authentication flow including OAuth and 2FA',
    startDate: '2026-04-21',
    endDate: '2026-05-02',
    committedPoints: 42,
    status: 'completed',
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-05-02T18:00:00.000Z',
  },
  {
    id: 'sprint-2',
    name: 'Sprint 13 - Dashboard & Reports',
    goal: 'Build main dashboard with analytics, reporting features and export capabilities',
    startDate: '2026-05-05',
    endDate: '2026-05-16',
    committedPoints: 38,
    status: 'active',
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-05T09:00:00.000Z',
  },
];

export const MOCK_STORIES: UserStory[] = [
  // Sprint 1 - Completed sprint stories
  {
    id: 'story-1',
    sprintId: 'sprint-1',
    title: 'User login with email/password',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/AUTH-1',
    priority: 'critical',
    points: 8,
    commitmentDate: '2026-04-25',
    status: 'done-prd',
    progress: 100,
    assignees: ['dev-1', 'dev-2'],
    isBlocked: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-28T16:00:00.000Z',
  },
  {
    id: 'story-2',
    sprintId: 'sprint-1',
    title: 'OAuth 2.0 Google integration',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/AUTH-2',
    priority: 'high',
    points: 5,
    commitmentDate: '2026-04-28',
    status: 'done-prd',
    progress: 100,
    assignees: ['dev-1'],
    isBlocked: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-29T14:00:00.000Z',
  },
  {
    id: 'story-3',
    sprintId: 'sprint-1',
    title: 'Two-factor authentication',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/AUTH-3',
    priority: 'high',
    points: 13,
    commitmentDate: '2026-04-30',
    status: 'done-prd',
    progress: 100,
    assignees: ['dev-2', 'dev-4'],
    isBlocked: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-05-01T10:00:00.000Z',
  },
  {
    id: 'story-4',
    sprintId: 'sprint-1',
    title: 'Password reset flow',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/AUTH-4',
    priority: 'medium',
    points: 5,
    commitmentDate: '2026-04-30',
    status: 'done-prd',
    progress: 100,
    assignees: ['dev-3'],
    isBlocked: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-30T15:00:00.000Z',
  },
  {
    id: 'story-5',
    sprintId: 'sprint-1',
    title: 'User session management',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/AUTH-5',
    priority: 'medium',
    points: 8,
    commitmentDate: '2026-05-01',
    status: 'done-prd',
    progress: 100,
    assignees: ['dev-2'],
    isBlocked: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-05-02T11:00:00.000Z',
  },

  // Sprint 2 - Active sprint stories
  {
    id: 'story-6',
    sprintId: 'sprint-2',
    title: 'Main dashboard layout',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-1',
    priority: 'critical',
    points: 8,
    commitmentDate: '2026-05-09',
    status: 'in-development',
    progress: 65,
    assignees: ['dev-1', 'dev-3'],
    isBlocked: false,
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-10T14:00:00.000Z',
  },
  {
    id: 'story-7',
    sprintId: 'sprint-2',
    title: 'Sales analytics chart',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-2',
    priority: 'high',
    points: 5,
    commitmentDate: '2026-05-12',
    status: 'open',
    progress: 25,
    assignees: ['dev-1'],
    isBlocked: false,
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-08T10:00:00.000Z',
  },
  {
    id: 'story-8',
    sprintId: 'sprint-2',
    title: 'PDF export functionality',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-3',
    priority: 'high',
    points: 8,
    commitmentDate: '2026-05-14',
    status: 'in-development',
    progress: 30,
    assignees: ['dev-2'],
    isBlocked: true,
    blockReason: 'Waiting for design approval on PDF template and branding guidelines',
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-09T09:00:00.000Z',
  },
  {
    id: 'story-9',
    sprintId: 'sprint-2',
    title: 'Real-time data updates via WebSocket',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-4',
    priority: 'medium',
    points: 5,
    commitmentDate: '2026-05-14',
    status: 'open',
    progress: 0,
    assignees: ['dev-2', 'dev-3'],
    isBlocked: false,
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-04T09:00:00.000Z',
  },
  {
    id: 'story-10',
    sprintId: 'sprint-2',
    title: 'User permissions & role management',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-5',
    priority: 'medium',
    points: 8,
    commitmentDate: '2026-05-15',
    status: 'in-certification',
    progress: 85,
    assignees: ['dev-3', 'dev-4'],
    isBlocked: false,
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-11T16:00:00.000Z',
  },
  {
    id: 'story-11',
    sprintId: 'sprint-2',
    title: 'Email notification system',
    jiraUrl: 'https://tuempresa.atlassian.net/browse/DASH-6',
    priority: 'low',
    points: 4,
    commitmentDate: '2026-05-15',
    status: 'open',
    progress: 0,
    assignees: [],
    isBlocked: false,
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-05-04T09:00:00.000Z',
  },
];

export const MOCK_HOLIDAYS: SprintHoliday[] = [
  {
    id: 'holiday-1',
    sprintId: 'sprint-2',
    date: '2026-05-09',
    description: 'Día del Trabajador Universitario',
  },
];

export const MOCK_AVAILABILITY: DeveloperAvailability[] = [
  {
    id: 'avail-1',
    sprintId: 'sprint-2',
    developerId: 'dev-3',
    daysOff: 2,
    reason: 'vacaciones',
    notes: 'Vacaciones anuales',
  },
  {
    id: 'avail-2',
    sprintId: 'sprint-2',
    developerId: 'dev-4',
    daysOff: 1,
    reason: 'licencia',
    notes: 'Licencia médica',
  },
];

export const MOCK_PROGRESS_RECORDS: ProgressRecord[] = [
  // Story 1 progress
  {
    id: 'prog-1',
    storyId: 'story-1',
    developerId: 'dev-1',
    timestamp: '2026-04-21T10:00:00.000Z',
    hoursWorked: 4,
    comment: 'Set up login form UI with validation',
    progressPercentage: 25,
    newStatus: 'in-development',
  },
  {
    id: 'prog-2',
    storyId: 'story-1',
    developerId: 'dev-2',
    timestamp: '2026-04-22T14:00:00.000Z',
    hoursWorked: 6,
    comment: 'JWT generation and refresh token logic implemented',
    progressPercentage: 60,
    newStatus: 'in-development',
  },
  {
    id: 'prog-3',
    storyId: 'story-1',
    developerId: 'dev-4',
    timestamp: '2026-04-25T09:00:00.000Z',
    hoursWorked: 3,
    comment: 'Testing login edge cases. All passing.',
    progressPercentage: 90,
    newStatus: 'in-certification',
  },
  {
    id: 'prog-4',
    storyId: 'story-1',
    developerId: 'dev-1',
    timestamp: '2026-04-28T16:00:00.000Z',
    hoursWorked: 2,
    comment: 'Fixed minor UI bugs, ready for deployment',
    progressPercentage: 100,
    newStatus: 'done-prd',
  },
  // Story 2 progress
  {
    id: 'prog-5',
    storyId: 'story-2',
    developerId: 'dev-1',
    timestamp: '2026-04-23T10:00:00.000Z',
    hoursWorked: 5,
    comment: 'OAuth flow implemented and tested with Google',
    progressPercentage: 70,
    newStatus: 'in-development',
  },
  {
    id: 'prog-6',
    storyId: 'story-2',
    developerId: 'dev-1',
    timestamp: '2026-04-29T14:00:00.000Z',
    hoursWorked: 3,
    comment: 'Profile picture sync done. QA passed.',
    progressPercentage: 100,
    newStatus: 'done-prd',
  },
  // Story 3 progress
  {
    id: 'prog-7',
    storyId: 'story-3',
    developerId: 'dev-2',
    timestamp: '2026-04-24T09:00:00.000Z',
    hoursWorked: 8,
    comment: 'TOTP library integrated, QR code generation working',
    progressPercentage: 50,
    newStatus: 'in-development',
  },
  {
    id: 'prog-8',
    storyId: 'story-3',
    developerId: 'dev-4',
    timestamp: '2026-04-29T14:00:00.000Z',
    hoursWorked: 4,
    comment: 'QA testing 2FA edge cases - all good',
    progressPercentage: 85,
    newStatus: 'in-certification',
  },
  {
    id: 'prog-9',
    storyId: 'story-3',
    developerId: 'dev-2',
    timestamp: '2026-05-01T10:00:00.000Z',
    hoursWorked: 3,
    comment: 'Backup codes implemented and tested',
    progressPercentage: 100,
    newStatus: 'done-prd',
  },
  // Story 4 progress
  {
    id: 'prog-10',
    storyId: 'story-4',
    developerId: 'dev-3',
    timestamp: '2026-04-25T10:00:00.000Z',
    hoursWorked: 4,
    comment: 'Email template and token generation complete',
    progressPercentage: 60,
    newStatus: 'in-development',
  },
  {
    id: 'prog-11',
    storyId: 'story-4',
    developerId: 'dev-3',
    timestamp: '2026-04-30T15:00:00.000Z',
    hoursWorked: 3,
    comment: 'Flow tested end-to-end, all working',
    progressPercentage: 100,
    newStatus: 'done-prd',
  },
  // Story 5 progress
  {
    id: 'prog-12',
    storyId: 'story-5',
    developerId: 'dev-2',
    timestamp: '2026-04-28T10:00:00.000Z',
    hoursWorked: 5,
    comment: 'Session tracking and device list implemented',
    progressPercentage: 60,
    newStatus: 'in-development',
  },
  {
    id: 'prog-13',
    storyId: 'story-5',
    developerId: 'dev-2',
    timestamp: '2026-05-02T11:00:00.000Z',
    hoursWorked: 4,
    comment: 'Logout all devices working. Tests green.',
    progressPercentage: 100,
    newStatus: 'done-prd',
  },
  // Sprint 2 stories progress
  {
    id: 'prog-14',
    storyId: 'story-6',
    developerId: 'dev-1',
    timestamp: '2026-05-05T10:00:00.000Z',
    hoursWorked: 4,
    comment: 'Dashboard grid layout structure set up',
    progressPercentage: 20,
    newStatus: 'in-development',
  },
  {
    id: 'prog-15',
    storyId: 'story-6',
    developerId: 'dev-3',
    timestamp: '2026-05-07T14:00:00.000Z',
    hoursWorked: 5,
    comment: 'KPI cards implemented with mock data',
    progressPercentage: 45,
    newStatus: 'in-development',
  },
  {
    id: 'prog-16',
    storyId: 'story-6',
    developerId: 'dev-1',
    timestamp: '2026-05-10T14:00:00.000Z',
    hoursWorked: 3,
    comment: 'Responsive layout polished, navigation integrated',
    progressPercentage: 65,
    newStatus: 'in-development',
  },
  {
    id: 'prog-17',
    storyId: 'story-7',
    developerId: 'dev-1',
    timestamp: '2026-05-08T10:00:00.000Z',
    hoursWorked: 3,
    comment: 'Data analysis and chart library selection done',
    progressPercentage: 25,
    newStatus: 'open',
  },
  {
    id: 'prog-18',
    storyId: 'story-8',
    developerId: 'dev-2',
    timestamp: '2026-05-06T09:00:00.000Z',
    hoursWorked: 4,
    comment: 'Started PDF library integration',
    progressPercentage: 20,
    newStatus: 'in-development',
  },
  {
    id: 'prog-19',
    storyId: 'story-8',
    developerId: 'dev-2',
    timestamp: '2026-05-09T09:00:00.000Z',
    hoursWorked: 2,
    comment: 'Blocked waiting for design team approval on templates',
    progressPercentage: 30,
    newStatus: 'in-development',
  },
  {
    id: 'prog-20',
    storyId: 'story-10',
    developerId: 'dev-3',
    timestamp: '2026-05-05T10:00:00.000Z',
    hoursWorked: 5,
    comment: 'RBAC middleware implemented',
    progressPercentage: 40,
    newStatus: 'in-development',
  },
  {
    id: 'prog-21',
    storyId: 'story-10',
    developerId: 'dev-4',
    timestamp: '2026-05-11T16:00:00.000Z',
    hoursWorked: 4,
    comment: 'QA testing all permission scenarios',
    progressPercentage: 85,
    newStatus: 'in-certification',
  },
];
